version: '3.9'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - ./app/.env
    ports:
      - 5455:5432

  redis:
    image: redis:latest
    ports:
      - 6380:6379

  server:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db
